import { useState } from 'react'
import * as Dialog from '@radix-ui/react-dialog'
import { X, Plus, Trash2 } from 'lucide-react'
import { nanoid } from 'nanoid'
import { useRCTStore } from '@/stores/rctStore'
import { useAddCustomColumn, useCustomColumns } from '@/hooks/useCustomColumns'
import { useIsDemoMode } from '@/hooks/useTenantData'
import { validateFormula } from '@/utils/formulaEngine'
import type { CustomColumn } from '@/types/rct'

interface AddColumnDialogProps {
  isOpen: boolean
  onClose: () => void
}

type ColumnType = CustomColumn['type']

export function AddColumnDialog({ isOpen, onClose }: AddColumnDialogProps) {
  const isDemoMode = useIsDemoMode()

  // Demo mode: use local store
  const { addCustomColumn: storeAddCustomColumn, customColumns: storeCustomColumns } = useRCTStore()

  // Authenticated mode: use database hooks
  const { data: dbCustomColumns } = useCustomColumns()
  const addCustomColumnMutation = useAddCustomColumn()

  // Use appropriate data source for formula validation
  const customColumns = isDemoMode ? storeCustomColumns : (dbCustomColumns || [])

  const [name, setName] = useState('')
  const [type, setType] = useState<ColumnType>('text')
  const [dropdownOptions, setDropdownOptions] = useState<string[]>([''])
  const [formula, setFormula] = useState('')
  const [formulaError, setFormulaError] = useState<string | null>(null)

  const resetForm = () => {
    setName('')
    setType('text')
    setDropdownOptions([''])
    setFormula('')
    setFormulaError(null)
  }

  const handleClose = () => {
    resetForm()
    onClose()
  }

  const handleFormulaChange = (value: string) => {
    setFormula(value)
    if (value.trim()) {
      const validation = validateFormula(value, customColumns)
      setFormulaError(validation.error)
    } else {
      setFormulaError(null)
    }
  }

  const addDropdownOption = () => {
    setDropdownOptions([...dropdownOptions, ''])
  }

  const updateDropdownOption = (index: number, value: string) => {
    const updated = [...dropdownOptions]
    updated[index] = value
    setDropdownOptions(updated)
  }

  const removeDropdownOption = (index: number) => {
    setDropdownOptions(dropdownOptions.filter((_, i) => i !== index))
  }

  const handleSubmit = () => {
    if (!name.trim()) return

    // Build column data
    const columnName = name.trim()
    const options = type === 'dropdown' ? dropdownOptions.filter(o => o.trim()) : undefined
    const formulaValue = type === 'formula' ? formula.trim() : undefined

    if (type === 'formula' && (!formulaValue || formulaError)) return

    if (isDemoMode) {
      // Demo mode: add to local store with generated ID
      const column: CustomColumn = {
        id: nanoid(),
        name: columnName,
        type,
        options,
        formula: formulaValue,
      }
      storeAddCustomColumn(column)
    } else {
      // Authenticated mode: add to database (ID generated by Supabase)
      addCustomColumnMutation.mutate({
        name: columnName,
        type,
        options,
        formula: formulaValue,
        sortOrder: customColumns.length, // Add at end
      })
    }

    handleClose()
  }

  const canSubmit = name.trim() &&
    (type !== 'formula' || (formula.trim() && !formulaError)) &&
    (type !== 'dropdown' || dropdownOptions.some(o => o.trim()))

  return (
    <Dialog.Root open={isOpen} onOpenChange={(open) => !open && handleClose()}>
      <Dialog.Portal>
        <Dialog.Overlay className="fixed inset-0 bg-black/60 z-40" />
        <Dialog.Content className="fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[440px] bg-surface-elevated border border-surface-border rounded-lg shadow-xl z-50">
          {/* Header */}
          <div className="flex items-center justify-between p-4 border-b border-surface-border">
            <Dialog.Title className="text-lg font-semibold text-text-primary">
              Add Custom Column
            </Dialog.Title>
            <Dialog.Close asChild>
              <button className="p-2 rounded-lg hover:bg-surface-overlay transition-colors">
                <X size={20} className="text-text-secondary" />
              </button>
            </Dialog.Close>
          </div>

          {/* Form */}
          <div className="p-4 space-y-4">
            {/* Name */}
            <div>
              <label className="block text-sm font-medium text-text-secondary mb-1.5">
                Column Name
              </label>
              <input
                type="text"
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="e.g., Owner, Due Date, Notes..."
                className="w-full px-3 py-2 bg-surface-overlay border border-surface-border rounded-lg text-sm text-text-primary placeholder:text-text-muted focus:outline-none focus:ring-2 focus:ring-accent-500"
              />
            </div>

            {/* Type */}
            <div>
              <label className="block text-sm font-medium text-text-secondary mb-1.5">
                Column Type
              </label>
              <select
                value={type}
                onChange={(e) => setType(e.target.value as ColumnType)}
                className="w-full px-3 py-2 bg-surface-overlay border border-surface-border rounded-lg text-sm text-text-primary focus:outline-none focus:ring-2 focus:ring-accent-500"
              >
                <option value="text">Text</option>
                <option value="number">Number</option>
                <option value="dropdown">Dropdown</option>
                <option value="date">Date</option>
                <option value="formula">Formula</option>
              </select>
            </div>

            {/* Dropdown options */}
            {type === 'dropdown' && (
              <div>
                <label className="block text-sm font-medium text-text-secondary mb-1.5">
                  Options
                </label>
                <div className="space-y-2">
                  {dropdownOptions.map((option, index) => (
                    <div key={index} className="flex gap-2">
                      <input
                        type="text"
                        value={option}
                        onChange={(e) => updateDropdownOption(index, e.target.value)}
                        placeholder={`Option ${index + 1}`}
                        className="flex-1 px-3 py-2 bg-surface-overlay border border-surface-border rounded-lg text-sm text-text-primary placeholder:text-text-muted focus:outline-none focus:ring-2 focus:ring-accent-500"
                      />
                      {dropdownOptions.length > 1 && (
                        <button
                          onClick={() => removeDropdownOption(index)}
                          className="p-2 text-text-muted hover:text-red-400 transition-colors"
                        >
                          <Trash2 size={16} />
                        </button>
                      )}
                    </div>
                  ))}
                  <button
                    onClick={addDropdownOption}
                    className="flex items-center gap-1 text-sm text-accent-500 hover:text-accent-400"
                  >
                    <Plus size={14} />
                    Add option
                  </button>
                </div>
              </div>
            )}

            {/* Formula */}
            {type === 'formula' && (
              <div>
                <label className="block text-sm font-medium text-text-secondary mb-1.5">
                  Formula
                </label>
                <input
                  type="text"
                  value={formula}
                  onChange={(e) => handleFormulaChange(e.target.value)}
                  placeholder="e.g., IF(Gross_Score>15,'High','Low')"
                  className="w-full px-3 py-2 bg-surface-overlay border border-surface-border rounded-lg text-sm text-text-primary placeholder:text-text-muted focus:outline-none focus:ring-2 focus:ring-accent-500 font-mono"
                />
                {formulaError && (
                  <p className="mt-1 text-xs text-red-400">{formulaError}</p>
                )}
                <p className="mt-1.5 text-xs text-text-muted">
                  Available: Gross_Score, Gross_Probability, Gross_Impact, Risk_Appetite, Within_Appetite, Net_Score, Control_Count
                  {customColumns.length > 0 && (
                    <>, {customColumns.map(c => c.name.replace(/\s/g, '_')).join(', ')}</>
                  )}
                </p>
              </div>
            )}
          </div>

          {/* Footer */}
          <div className="flex justify-end gap-2 p-4 border-t border-surface-border">
            <button
              onClick={handleClose}
              className="px-4 py-2 text-sm text-text-secondary hover:text-text-primary transition-colors"
            >
              Cancel
            </button>
            <button
              onClick={handleSubmit}
              disabled={!canSubmit}
              className="px-4 py-2 bg-accent-500 text-white rounded-lg text-sm font-medium hover:bg-accent-600 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              Add Column
            </button>
          </div>
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  )
}
