-- Seed Script: 29-02-process-taxonomy.sql
-- Purpose: Create process taxonomy (L1-L5) for demo tenant
-- Tenant: 5ea03edb-6e79-4b62-bd36-39f1963d0640
-- Phase: 29-demo-tenant-seed-data
--
-- Execute in Supabase SQL Editor or via psql
-- hierarchical_id is auto-generated by trigger (do not insert directly)

DO $$
DECLARE
  v_tenant_id UUID := '5ea03edb-6e79-4b62-bd36-39f1963d0640';

  -- L1 categories
  l1_core_ops UUID;
  l1_sales UUID;
  l1_support UUID;
  l1_procurement UUID;
  l1_management UUID;
  l1_compliance UUID;

  -- L2 under Core Operations
  l2_production UUID;
  l2_quality UUID;
  l2_logistics UUID;
  l2_customer_svc UUID;

  -- L2 under Sales & Marketing
  l2_bizdev UUID;
  l2_account_mgmt UUID;
  l2_marketing UUID;
  l2_pricing UUID;

  -- L2 under Support Functions
  l2_finance UUID;
  l2_hr UUID;
  l2_it UUID;
  l2_facilities UUID;

  -- L2 under Procurement
  l2_sourcing UUID;
  l2_purchasing UUID;
  l2_vendor UUID;

  -- L2 under Management
  l2_strategic UUID;
  l2_performance UUID;
  l2_project UUID;

  -- L2 under Compliance & Risk
  l2_regulatory UUID;
  l2_audit UUID;
  l2_risk_mgmt UUID;

  -- L3 for deep hierarchy branches
  l3_financial_reporting UUID;
  l3_manufacturing UUID;

  -- L4 for deep hierarchy branches
  l4_regulatory_filings UUID;
  l4_assembly UUID;

BEGIN
  -- Clean slate: Delete existing process taxonomy nodes for this tenant
  DELETE FROM public.taxonomy_nodes
  WHERE tenant_id = v_tenant_id AND type = 'process';

  -- ============================================================
  -- L1: Top-level process categories (6 total)
  -- ============================================================

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', NULL, 'Core Operations', 'Primary business operations that deliver products or services to customers', 1)
  RETURNING id INTO l1_core_ops;

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', NULL, 'Sales & Marketing', 'Revenue generation activities including sales, marketing, and customer acquisition', 2)
  RETURNING id INTO l1_sales;

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', NULL, 'Support Functions', 'Internal support services enabling core business operations', 3)
  RETURNING id INTO l1_support;

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', NULL, 'Procurement', 'Acquisition of goods and services from external suppliers', 4)
  RETURNING id INTO l1_procurement;

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', NULL, 'Management', 'Strategic planning, governance, and organizational oversight', 5)
  RETURNING id INTO l1_management;

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', NULL, 'Compliance & Risk', 'Regulatory compliance, risk management, and internal controls', 6)
  RETURNING id INTO l1_compliance;

  -- ============================================================
  -- L2: Core Operations subcategories (4)
  -- ============================================================

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l1_core_ops, 'Production/Service Delivery', 'Manufacturing products or delivering services to customers', 1)
  RETURNING id INTO l2_production;

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l1_core_ops, 'Quality Assurance', 'Ensuring products and services meet quality standards', 2)
  RETURNING id INTO l2_quality;

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l1_core_ops, 'Logistics & Distribution', 'Movement and storage of goods through the supply chain', 3)
  RETURNING id INTO l2_logistics;

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l1_core_ops, 'Customer Service', 'Post-sale support and customer relationship management', 4)
  RETURNING id INTO l2_customer_svc;

  -- ============================================================
  -- L2: Sales & Marketing subcategories (4)
  -- ============================================================

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l1_sales, 'Business Development', 'Identifying and pursuing new business opportunities', 1)
  RETURNING id INTO l2_bizdev;

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l1_sales, 'Account Management', 'Managing relationships with existing customers', 2)
  RETURNING id INTO l2_account_mgmt;

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l1_sales, 'Marketing', 'Brand promotion, advertising, and market communication', 3)
  RETURNING id INTO l2_marketing;

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l1_sales, 'Pricing & Contracts', 'Setting prices and managing contractual agreements', 4)
  RETURNING id INTO l2_pricing;

  -- ============================================================
  -- L2: Support Functions subcategories (4)
  -- ============================================================

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l1_support, 'Finance & Accounting', 'Financial management, reporting, and accounting operations', 1)
  RETURNING id INTO l2_finance;

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l1_support, 'Human Resources', 'Employee lifecycle management and workforce development', 2)
  RETURNING id INTO l2_hr;

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l1_support, 'Information Technology', 'Technology infrastructure and digital services', 3)
  RETURNING id INTO l2_it;

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l1_support, 'Facilities & Administration', 'Physical workspace and administrative operations', 4)
  RETURNING id INTO l2_facilities;

  -- ============================================================
  -- L2: Procurement subcategories (3)
  -- ============================================================

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l1_procurement, 'Sourcing', 'Identifying and evaluating potential suppliers', 1)
  RETURNING id INTO l2_sourcing;

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l1_procurement, 'Purchasing', 'Processing purchase orders and managing transactions', 2)
  RETURNING id INTO l2_purchasing;

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l1_procurement, 'Vendor Management', 'Managing supplier relationships and performance', 3)
  RETURNING id INTO l2_vendor;

  -- ============================================================
  -- L2: Management subcategories (3)
  -- ============================================================

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l1_management, 'Strategic Planning', 'Long-term organizational direction and goal setting', 1)
  RETURNING id INTO l2_strategic;

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l1_management, 'Performance Management', 'Measuring and improving organizational performance', 2)
  RETURNING id INTO l2_performance;

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l1_management, 'Project Management', 'Planning and executing organizational initiatives', 3)
  RETURNING id INTO l2_project;

  -- ============================================================
  -- L2: Compliance & Risk subcategories (3)
  -- ============================================================

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l1_compliance, 'Regulatory Compliance', 'Ensuring adherence to laws and regulations', 1)
  RETURNING id INTO l2_regulatory;

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l1_compliance, 'Internal Audit', 'Independent evaluation of internal controls and processes', 2)
  RETURNING id INTO l2_audit;

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l1_compliance, 'Risk Management', 'Identifying and mitigating organizational risks', 3)
  RETURNING id INTO l2_risk_mgmt;

  -- ============================================================
  -- L3: Production/Service Delivery children (2) - includes deep branch
  -- ============================================================

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l2_production, 'Manufacturing', 'Physical production of goods and components', 1)
  RETURNING id INTO l3_manufacturing;

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l2_production, 'Service Execution', 'Delivery of professional or technical services', 2);

  -- ============================================================
  -- L3: Quality Assurance children (2)
  -- ============================================================

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l2_quality, 'Quality Control', 'Inspection and testing of products or services', 1);

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l2_quality, 'Continuous Improvement', 'Ongoing enhancement of quality processes', 2);

  -- ============================================================
  -- L3: Finance & Accounting children (3) - includes deep branch
  -- ============================================================

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l2_finance, 'Accounts Payable', 'Processing vendor invoices and payments', 1);

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l2_finance, 'Accounts Receivable', 'Managing customer invoicing and collections', 2);

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l2_finance, 'Financial Reporting', 'Preparing financial statements and reports', 3)
  RETURNING id INTO l3_financial_reporting;

  -- ============================================================
  -- L3: Human Resources children (3)
  -- ============================================================

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l2_hr, 'Recruitment', 'Attracting and hiring qualified candidates', 1);

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l2_hr, 'Training & Development', 'Employee skill development and learning programs', 2);

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l2_hr, 'Compensation & Benefits', 'Managing employee pay and benefit programs', 3);

  -- ============================================================
  -- L3: Information Technology children (3)
  -- ============================================================

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l2_it, 'Infrastructure Management', 'Managing servers, networks, and hardware', 1);

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l2_it, 'Application Management', 'Supporting and maintaining business applications', 2);

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l2_it, 'Cybersecurity', 'Protecting systems and data from threats', 3);

  -- ============================================================
  -- L3: Sourcing children (2)
  -- ============================================================

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l2_sourcing, 'Supplier Identification', 'Finding and evaluating potential suppliers', 1);

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l2_sourcing, 'Supplier Evaluation', 'Assessing supplier capabilities and fit', 2);

  -- ============================================================
  -- L3: Purchasing children (2)
  -- ============================================================

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l2_purchasing, 'Purchase Order Processing', 'Creating and managing purchase orders', 1);

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l2_purchasing, 'Receiving & Inspection', 'Verifying receipt and quality of purchases', 2);

  -- ============================================================
  -- L3: Vendor Management children (2)
  -- ============================================================

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l2_vendor, 'Vendor Onboarding', 'Setting up new vendors in systems', 1);

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l2_vendor, 'Performance Monitoring', 'Tracking vendor performance metrics', 2);

  -- ============================================================
  -- L3: Regulatory Compliance children (2)
  -- ============================================================

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l2_regulatory, 'Regulatory Monitoring', 'Tracking regulatory changes and requirements', 1);

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l2_regulatory, 'Compliance Assessment', 'Evaluating compliance with regulations', 2);

  -- ============================================================
  -- L3: Risk Management children (2)
  -- ============================================================

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l2_risk_mgmt, 'Risk Identification', 'Identifying potential risks to the organization', 1);

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l2_risk_mgmt, 'Risk Mitigation', 'Implementing controls to reduce risk exposure', 2);

  -- ============================================================
  -- L4/L5: Deep hierarchy branches (to showcase depth)
  -- ============================================================

  -- Branch 1: Support Functions -> Finance & Accounting -> Financial Reporting -> Regulatory Filings -> Annual Report (L5)
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l3_financial_reporting, 'Regulatory Filings', 'Preparing and submitting required regulatory financial reports', 1)
  RETURNING id INTO l4_regulatory_filings;

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l4_regulatory_filings, 'Annual Report', 'Comprehensive yearly financial report for stakeholders', 1);

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l4_regulatory_filings, 'Quarterly Filings', 'Periodic financial reports required by regulators', 2);

  -- Branch 2: Core Operations -> Production -> Manufacturing -> Assembly -> Final Assembly (L5)
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l3_manufacturing, 'Assembly', 'Putting together components into finished products', 1)
  RETURNING id INTO l4_assembly;

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l4_assembly, 'Sub-Assembly', 'Creating intermediate component assemblies', 1);

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'process', l4_assembly, 'Final Assembly', 'Completing the final product assembly', 2);

  -- ============================================================
  -- Summary:
  -- L1: 6 nodes
  -- L2: 21 nodes (4+4+4+3+3+3)
  -- L3: 23 nodes (selective L2s have children)
  -- L4: 2 nodes (Regulatory Filings, Assembly)
  -- L5: 4 nodes (Annual Report, Quarterly Filings, Sub-Assembly, Final Assembly)
  -- Total: 56 nodes
  -- ============================================================

END $$;
