-- Seed Script: 29-01-risk-taxonomy.sql
-- Purpose: Populate demo tenant with generic enterprise risk taxonomy (L1-L5)
-- Tenant ID: 5ea03edb-6e79-4b62-bd36-39f1963d0640
-- Total Nodes: 61 risk taxonomy nodes across 5 hierarchy levels
--
-- Structure:
--   L1: 5 categories (Strategic, Operational, Financial, Compliance, Technology)
--   L2: 16 subcategories (3-4 per L1)
--   L3: 32 specific risk types (2-3 per L2)
--   L4/L5: 2 deep branches to showcase hierarchy depth (8 nodes)
--
-- Usage: Execute in Supabase SQL Editor or via psql
-- Note: hierarchical_id and path are auto-generated by trigger

DO $$
DECLARE
  v_tenant_id UUID := '5ea03edb-6e79-4b62-bd36-39f1963d0640';

  -- L1 IDs
  l1_strategic UUID;
  l1_operational UUID;
  l1_financial UUID;
  l1_compliance UUID;
  l1_technology UUID;

  -- L2 IDs - Strategic
  l2_market UUID;
  l2_business_model UUID;
  l2_growth UUID;

  -- L2 IDs - Operational
  l2_process UUID;
  l2_people UUID;
  l2_supply_chain UUID;
  l2_physical_asset UUID;

  -- L2 IDs - Financial
  l2_liquidity UUID;
  l2_credit UUID;
  l2_market_price UUID;

  -- L2 IDs - Compliance
  l2_regulatory UUID;
  l2_legal UUID;
  l2_data_privacy UUID;

  -- L2 IDs - Technology
  l2_cybersecurity UUID;
  l2_system UUID;
  l2_data UUID;

  -- L3 IDs (for L4/L5 branches)
  l3_data_breach UUID;
  l3_industry_specific UUID;

  -- L4 IDs
  l4_external_attack UUID;
  l4_license_requirements UUID;

BEGIN
  -- Clean slate: Delete existing risk taxonomy for this tenant
  DELETE FROM public.taxonomy_nodes
  WHERE tenant_id = v_tenant_id AND type = 'risk';

  -- ============================================================
  -- L1: STRATEGIC RISK
  -- ============================================================
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'risk', NULL, 'Strategic Risk', 'Risks affecting long-term business goals and competitive position', 1)
  RETURNING id INTO l1_strategic;

  -- L2: Market Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'risk', l1_strategic, 'Market Risk', 'Risks from external market conditions and competitive landscape', 1)
  RETURNING id INTO l2_market;

  -- L3 under Market Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order) VALUES
    (v_tenant_id, 'risk', l2_market, 'Competition', 'Risks from existing or new market competitors', 1),
    (v_tenant_id, 'risk', l2_market, 'Market Disruption', 'Risks from technological or business model disruption', 2);

  -- L2: Business Model Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'risk', l1_strategic, 'Business Model Risk', 'Risks to the viability of current business model', 2)
  RETURNING id INTO l2_business_model;

  -- L3 under Business Model Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order) VALUES
    (v_tenant_id, 'risk', l2_business_model, 'Revenue Model Obsolescence', 'Risks from changing customer preferences or technology', 1),
    (v_tenant_id, 'risk', l2_business_model, 'Partnership Dependency', 'Risks from over-reliance on key business partners', 2);

  -- L2: Growth Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'risk', l1_strategic, 'Growth Risk', 'Risks associated with expansion and growth initiatives', 3)
  RETURNING id INTO l2_growth;

  -- L3 under Growth Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order) VALUES
    (v_tenant_id, 'risk', l2_growth, 'Market Entry Failure', 'Risks from unsuccessful new market expansion', 1),
    (v_tenant_id, 'risk', l2_growth, 'Scaling Challenges', 'Risks from inability to scale operations effectively', 2);

  -- ============================================================
  -- L1: OPERATIONAL RISK
  -- ============================================================
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'risk', NULL, 'Operational Risk', 'Risks from internal processes, people, and systems', 2)
  RETURNING id INTO l1_operational;

  -- L2: Process Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'risk', l1_operational, 'Process Risk', 'Risks from business process failures or inefficiencies', 1)
  RETURNING id INTO l2_process;

  -- L3 under Process Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order) VALUES
    (v_tenant_id, 'risk', l2_process, 'Process Failure', 'Risks from breakdown in critical business processes', 1),
    (v_tenant_id, 'risk', l2_process, 'Quality Control', 'Risks from inadequate quality assurance procedures', 2);

  -- L2: People Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'risk', l1_operational, 'People Risk', 'Risks from workforce-related issues', 2)
  RETURNING id INTO l2_people;

  -- L3 under People Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order) VALUES
    (v_tenant_id, 'risk', l2_people, 'Key Person Dependency', 'Risks from over-reliance on critical individuals', 1),
    (v_tenant_id, 'risk', l2_people, 'Skills Gap', 'Risks from insufficient workforce skills or training', 2);

  -- L2: Supply Chain Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'risk', l1_operational, 'Supply Chain Risk', 'Risks from supplier and logistics dependencies', 3)
  RETURNING id INTO l2_supply_chain;

  -- L3 under Supply Chain Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order) VALUES
    (v_tenant_id, 'risk', l2_supply_chain, 'Supplier Failure', 'Risks from critical supplier business disruption', 1),
    (v_tenant_id, 'risk', l2_supply_chain, 'Logistics Disruption', 'Risks from transportation or distribution failures', 2);

  -- L2: Physical Asset Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'risk', l1_operational, 'Physical Asset Risk', 'Risks to physical infrastructure and assets', 4)
  RETURNING id INTO l2_physical_asset;

  -- L3 under Physical Asset Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order) VALUES
    (v_tenant_id, 'risk', l2_physical_asset, 'Equipment Failure', 'Risks from breakdown of critical equipment', 1),
    (v_tenant_id, 'risk', l2_physical_asset, 'Facility Damage', 'Risks from physical damage to buildings or facilities', 2);

  -- ============================================================
  -- L1: FINANCIAL RISK
  -- ============================================================
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'risk', NULL, 'Financial Risk', 'Risks affecting financial performance and stability', 3)
  RETURNING id INTO l1_financial;

  -- L2: Liquidity Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'risk', l1_financial, 'Liquidity Risk', 'Risks from inability to meet short-term obligations', 1)
  RETURNING id INTO l2_liquidity;

  -- L3 under Liquidity Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order) VALUES
    (v_tenant_id, 'risk', l2_liquidity, 'Cash Flow Shortage', 'Risks from insufficient cash to fund operations', 1),
    (v_tenant_id, 'risk', l2_liquidity, 'Working Capital Strain', 'Risks from inadequate working capital management', 2);

  -- L2: Credit Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'risk', l1_financial, 'Credit Risk', 'Risks from counterparty default or payment failures', 2)
  RETURNING id INTO l2_credit;

  -- L3 under Credit Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order) VALUES
    (v_tenant_id, 'risk', l2_credit, 'Customer Default', 'Risks from customers failing to pay receivables', 1),
    (v_tenant_id, 'risk', l2_credit, 'Counterparty Failure', 'Risks from business partner financial distress', 2);

  -- L2: Market Price Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'risk', l1_financial, 'Market Price Risk', 'Risks from adverse movements in market prices', 3)
  RETURNING id INTO l2_market_price;

  -- L3 under Market Price Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order) VALUES
    (v_tenant_id, 'risk', l2_market_price, 'Currency Fluctuation', 'Risks from foreign exchange rate movements', 1),
    (v_tenant_id, 'risk', l2_market_price, 'Interest Rate', 'Risks from changes in interest rates', 2);

  -- ============================================================
  -- L1: COMPLIANCE RISK
  -- ============================================================
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'risk', NULL, 'Compliance Risk', 'Risks from regulatory and legal obligations', 4)
  RETURNING id INTO l1_compliance;

  -- L2: Regulatory Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'risk', l1_compliance, 'Regulatory Risk', 'Risks from regulatory requirements and changes', 1)
  RETURNING id INTO l2_regulatory;

  -- L3 under Regulatory Risk (with L4/L5 branch)
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order) VALUES
    (v_tenant_id, 'risk', l2_regulatory, 'Regulatory Change', 'Risks from new or changing regulations', 1),
    (v_tenant_id, 'risk', l2_regulatory, 'Reporting Compliance', 'Risks from regulatory reporting requirements', 2);

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'risk', l2_regulatory, 'Industry Specific', 'Risks from industry-specific regulatory requirements', 3)
  RETURNING id INTO l3_industry_specific;

  -- L4 under Industry Specific
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'risk', l3_industry_specific, 'License Requirements', 'Risks from professional or business licensing', 1)
  RETURNING id INTO l4_license_requirements;

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order) VALUES
    (v_tenant_id, 'risk', l3_industry_specific, 'Certification Standards', 'Risks from industry certification compliance', 2);

  -- L5 under License Requirements
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order) VALUES
    (v_tenant_id, 'risk', l4_license_requirements, 'Annual Renewal', 'Risks from license renewal deadlines and requirements', 1),
    (v_tenant_id, 'risk', l4_license_requirements, 'Continuing Education', 'Risks from professional development requirements', 2);

  -- L2: Legal Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'risk', l1_compliance, 'Legal Risk', 'Risks from legal disputes and liability', 2)
  RETURNING id INTO l2_legal;

  -- L3 under Legal Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order) VALUES
    (v_tenant_id, 'risk', l2_legal, 'Contract Disputes', 'Risks from contractual disagreements or breaches', 1),
    (v_tenant_id, 'risk', l2_legal, 'Intellectual Property', 'Risks from IP infringement or protection failures', 2);

  -- L2: Data Privacy Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'risk', l1_compliance, 'Data Privacy Risk', 'Risks from data protection requirements', 3)
  RETURNING id INTO l2_data_privacy;

  -- L3 under Data Privacy Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order) VALUES
    (v_tenant_id, 'risk', l2_data_privacy, 'GDPR Compliance', 'Risks from EU data protection regulation requirements', 1),
    (v_tenant_id, 'risk', l2_data_privacy, 'Data Subject Rights', 'Risks from handling data access and deletion requests', 2);

  -- ============================================================
  -- L1: TECHNOLOGY RISK
  -- ============================================================
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'risk', NULL, 'Technology Risk', 'Risks from technology systems and digital assets', 5)
  RETURNING id INTO l1_technology;

  -- L2: Cybersecurity Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'risk', l1_technology, 'Cybersecurity Risk', 'Risks from cyber threats and security vulnerabilities', 1)
  RETURNING id INTO l2_cybersecurity;

  -- L3 under Cybersecurity Risk (with L4/L5 branch)
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'risk', l2_cybersecurity, 'Data Breach', 'Risks from unauthorized access to sensitive data', 1)
  RETURNING id INTO l3_data_breach;

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order) VALUES
    (v_tenant_id, 'risk', l2_cybersecurity, 'Ransomware', 'Risks from malicious encryption of systems', 2),
    (v_tenant_id, 'risk', l2_cybersecurity, 'Phishing', 'Risks from social engineering attacks', 3);

  -- L4 under Data Breach
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'risk', l3_data_breach, 'External Attack', 'Risks from external hacking attempts', 1)
  RETURNING id INTO l4_external_attack;

  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order) VALUES
    (v_tenant_id, 'risk', l3_data_breach, 'Accidental Disclosure', 'Risks from unintentional data exposure', 2);

  -- L5 under External Attack
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order) VALUES
    (v_tenant_id, 'risk', l4_external_attack, 'APT', 'Risks from advanced persistent threat actors', 1),
    (v_tenant_id, 'risk', l4_external_attack, 'Zero-Day Exploit', 'Risks from unknown vulnerability exploitation', 2);

  -- L2: System Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'risk', l1_technology, 'System Risk', 'Risks from IT system failures and reliability', 2)
  RETURNING id INTO l2_system;

  -- L3 under System Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order) VALUES
    (v_tenant_id, 'risk', l2_system, 'System Outage', 'Risks from unplanned system downtime', 1),
    (v_tenant_id, 'risk', l2_system, 'Legacy Systems', 'Risks from outdated technology dependencies', 2);

  -- L2: Data Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order)
  VALUES (v_tenant_id, 'risk', l1_technology, 'Data Risk', 'Risks to data integrity, availability, and quality', 3)
  RETURNING id INTO l2_data;

  -- L3 under Data Risk
  INSERT INTO public.taxonomy_nodes (tenant_id, type, parent_id, name, description, sort_order) VALUES
    (v_tenant_id, 'risk', l2_data, 'Data Loss', 'Risks from permanent loss of critical data', 1),
    (v_tenant_id, 'risk', l2_data, 'Data Corruption', 'Risks from data integrity failures', 2);

  -- Done - raise notice with count
  RAISE NOTICE 'Risk taxonomy seed complete. Inserted % nodes.',
    (SELECT COUNT(*) FROM public.taxonomy_nodes WHERE tenant_id = v_tenant_id AND type = 'risk');

END $$;

-- Verification query (run after execution to confirm):
-- SELECT hierarchical_id, name, description
-- FROM public.taxonomy_nodes
-- WHERE tenant_id = '5ea03edb-6e79-4b62-bd36-39f1963d0640' AND type = 'risk'
-- ORDER BY hierarchical_id;
